name: Bump version (stage)

on:
  pull_request:
    types:
      - closed

jobs:
  bump_version:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'stage'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Get latest tag for stage
        id: get_tag
        run: |
          latest_tag=$(git tag --list 'v*-stage' --sort=-v:refname | head -n 1)
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Bump version and push tag (stage)
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 1.2.3
          WITH_V: true
          PRERELEASE: true
          PRERELEASE_SUFFIX: "stage"
          DEFAULT_BUMP: patch # Change to major/minor/patch based on needs
          RELEASE_BRANCHES: stage
